//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fqtd.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandCategories
    {
        public int BrandID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<bool> Checked { get; set; }
    
        public virtual Brands tbl_Brands { get; set; }
        public virtual Categories tbl_Categories { get; set; }
    }
}
