//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fqtd.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrandItems
    {
        public BrandItems()
        {
            this.tbl_Item_Properties = new HashSet<ItemProperties>();
        }
    
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemName_EN { get; set; }
        public string Description { get; set; }
        public string Description_EN { get; set; }
        public string OpenTime { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public int BrandID { get; set; }
        public Nullable<decimal> SearchCount { get; set; }
        public Nullable<decimal> ClickCount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUser { get; set; }
        public string MarkerIcon { get; set; }
        public string Keyword { get; set; }
        public string Keyword_unsign { get; set; }
    
        public virtual Brands tbl_Brands { get; set; }
        public virtual ItemLocation tbl_Item_Location { get; set; }
        public virtual ICollection<ItemProperties> tbl_Item_Properties { get; set; }
    }
}
