//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fqtd.Areas.Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class fqtdEntities : DbContext
    {
        public fqtdEntities()
            : base("name=fqtdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BrandItems> BrandItems { get; set; }
        public DbSet<Brands> Brands { get; set; }
        public DbSet<BrandType> BrandTypes { get; set; }
        public DbSet<Categories> Categories { get; set; }
        public DbSet<ItemLocation> ItemLocations { get; set; }
        public DbSet<ItemProperties> ItemProperties { get; set; }
        public DbSet<Properties> Properties { get; set; }
    
        public virtual ObjectResult<SP_Category_Properties_Result> SP_Category_Properties(Nullable<int> categoryID)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Category_Properties_Result>("SP_Category_Properties", categoryIDParameter);
        }
    
        public virtual ObjectResult<SP_Item_Properties_Result> SP_Item_Properties(Nullable<int> itemID)
        {
            var itemIDParameter = itemID.HasValue ?
                new ObjectParameter("ItemID", itemID) :
                new ObjectParameter("ItemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Item_Properties_Result>("SP_Item_Properties", itemIDParameter);
        }
    
        public virtual ObjectResult<SP_GetKeyword1_Result> SP_GetKeyword1(string street, string district, string city)
        {
            var streetParameter = street != null ?
                new ObjectParameter("street", street) :
                new ObjectParameter("street", typeof(string));
    
            var districtParameter = district != null ?
                new ObjectParameter("district", district) :
                new ObjectParameter("district", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetKeyword1_Result>("SP_GetKeyword1", streetParameter, districtParameter, cityParameter);
        }
    }
}
