//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fqtd.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Properties
    {
        public Properties()
        {
            this.tbl_Item_Properties = new HashSet<ItemProperties>();
            this.tbl_Categories = new HashSet<Categories>();
        }
    
        public int PropertyID { get; set; }
        public string PropertyName { get; set; }
        public string PropertyName_EN { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUser { get; set; }
    
        public virtual ICollection<ItemProperties> tbl_Item_Properties { get; set; }
        public virtual ICollection<Categories> tbl_Categories { get; set; }
    }
}
