//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fqtd.Areas.Admin.Models
{
    using System;
    
    public enum SystemContent : int
    {
        Contact = 1,
        Introduction = 2,
        Tern4Use = 3,
        Policy = 4
    }
}
