//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fqtd.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Brand_Properties
    {
        public int BrandID { get; set; }
        public int PropertyID { get; set; }
        public bool PropertyValue { get; set; }
    
        public virtual Properties tbl_Properties { get; set; }
    }
}
