//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fqtd.Areas.Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchHistory
    {
        public int SearchID { get; set; }
        public string Keyword { get; set; }
        public string CurrentLocation { get; set; }
        public Nullable<int> Radious { get; set; }
        public string Properties { get; set; }
        public Nullable<int> Mode { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> VN0_En1 { get; set; }
        public Nullable<System.DateTime> SearchDate { get; set; }
        public Nullable<System.DateTime> SearchTime { get; set; }
        public Nullable<int> ResultCount { get; set; }
    }
}
